name: Enterprise Release

on:
  release:
    types: [created]

permissions: write-all

jobs:
  test:
    name: Run Tests
    runs-on: enterprise
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: Run Tests
        run: go test -v ./...

  releases-matrix:
    name: Release Go Binary
    runs-on: enterprise
    needs: test
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      
      - uses: wangyoucao577/go-release-action@v1
        id: build_release
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          project_path: ./cmd/hclsemver
          binary_name: "hclsemver"
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: "-s -w -extldflags '-static'"
          goversion: "1.23"
          upload: "FALSE"

      - name: Extract Tag Name
        id: extract_tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Copy, Package, and Rename Binary in /tmp
        run: |
          BINARY_NAME="hclsemver-${{ steps.extract_tag.outputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          cp ${{ steps.build_release.outputs.release_asset_dir }}/hclsemver /tmp/$BINARY_NAME
          chmod +rw /tmp/$BINARY_NAME
          tar -czvf /tmp/$BINARY_NAME.tar.gz -C /tmp $BINARY_NAME
          echo "PACKAGE_PATH=/tmp/$BINARY_NAME.tar.gz" >> $GITHUB_ENV
          ls -lah /tmp/$BINARY_NAME.tar.gz

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /tmp/hclsemver-${{ steps.extract_tag.outputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }} 