name: Release

on:
  release:
    types: [created]

permissions: write-all

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      
      - uses: wangyoucao577/go-release-action@v1
        id: build_release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: ./cmd/hclsemver
          binary_name: "hclsemver"
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: "-s -w -extldflags '-static'"
          goversion: "1.23"
          upload: "FALSE"

      - name: Extract Tag Name
        id: extract_tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Copy, Package, and Rename Binary in /tmp
        run: |
          BINARY_NAME="hclsemver-${{ steps.extract_tag.outputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          cp ${{ steps.build_release.outputs.release_asset_dir }}/hclsemver /tmp/$BINARY_NAME
          chmod +rw /tmp/$BINARY_NAME
          tar -czvf /tmp/$BINARY_NAME.tar.gz -C /tmp $BINARY_NAME
          echo "PACKAGE_PATH=/tmp/$BINARY_NAME.tar.gz" >> $GITHUB_ENV
          ls -lah /tmp/$BINARY_NAME.tar.gz

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /tmp/hclsemver-${{ steps.extract_tag.outputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: releases-matrix
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract Tag Name
        id: extract_tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/hclsemver:latest
            ${{ vars.DOCKERHUB_USERNAME }}/hclsemver:${{ steps.extract_tag.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
